version: "3.8"

secrets:
  analytics_connections:
    file: ./analytics_connections.yml
  analytics_secret:
    file: ./analytics_secret.txt

volumes:
  influxdb2_data:

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: uma-org
      DOCKER_INFLUXDB_INIT_BUCKET: testdb
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - influxdb2_data:/var/lib/influxdb2
    # v2 does NOT use influxdb.conf or a custom 'influxd -config ...' command
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8086/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  data_handler:
    # IMPORTANT: this image must be rebuilt to use the v2 python client (influxdb_client)
    image: 5genesis-analytics/data-handler:v2
    ports:
      - "5000:5000"
    secrets:
      - analytics_connections
    environment:
      ENABLE_CACHE: "true"
      ANALYTICS_CONN_FILE: "/run/secrets/analytics_connections"

  correlation:
    image: 5genesis-analytics/correlation:v2
    ports:
      - "5001:5001"

  prediction:
    image: 5genesis-analytics/prediction:v2
    ports:
      - "5002:5002"

  statistical_analysis:
    image: 5genesis-analytics/statistical-analysis:v2
    ports:
      - "5003:5003"

  feature_selection:
    image: 5genesis-analytics/feature-selection:v2
    ports:
      - "5004:5004"

  visualization:
    image: 5genesis-analytics/visualization:1.0.1
    ports:
      - "5005:5005"
    secrets:
      - analytics_secret
